language: python
sudo: false
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - "pip install -e ."
  - "pip install coveralls"
  - "pip install pyflakes"
  - "pip install pycodestyle"
  - "pip install pylint"

script:
  - "coverage run --source=validation setup.py test"
  - "pycodestyle validation setup.py"
  - "pyflakes validation setup.py"
  - "pylint -E validation setup.py"

after_success:
  - "coveralls"

deploy:
  - provider: pypi
    distributions: "sdist --formats=zip"
    user: "bwhmather-travis"
    password:
      secure: "rLlDjRwGY41G4DGU3g54RRkigMRHlFkffckVL+UpgRLaIWbTvvMfwDZvViMNsABxKS9Mwgf/D3Xls+DvimMY5is9l2bMQsW9MgQN+icnZFGgY+dnQD9ylSWcxn5U+/P0BTz1WIY4cA41Rjqv0aE23FKwkUYgfkdvYz51IrcvMbrvoo7LgTAPgF43r1LJAysv5A0Q4xdiKrl3d/9KfiDAS9PA6CXWMj7EXNzoUEl8UoycUwKsTx7hHthmsQrHIBPb7oB0xuKo5UtCYHlAXvIfD7VCbg4O5kLVb/f4m+Uo0eRpLw3RMtV/VJ/jK6UROZgixSP0Dryg9uP9/S3Ei/XgWnpWX4JRQ9ZQZW3tvo6YvQL/uVwsOpvbwhTJuIh+HUHGyVUwZvMsL2x53qnroJHffhvdnKji5p8ITJW6YPFovoZMktl9PLr/4ZprmY/pYFdJKMjOJuOpRTBctAmVX3d20oR9TWsliHb4D2CDOukmWT1iw9ogJwIDsGxqHt5GC/Rfe6Zb7k+GogMASXwGmw/D1n2SKbayryC+ngWoR7TEFdG78K0vCciu8Faq+sOeb8NCJl/cxBiOPvwD3LDnH5OSB/HM4sGF9pU2XnTUv41osP1wsPUCB7t61vj+J4sV0pgfvFHKzRkgZV5qCwbxq0DyFgmJqESPjs7WLQAI2sU3MHA="
    on:
      branch: "master"
      condition: "\"${TRAVIS_PYTHON_VERSION}\" = '3.6'"
