name: CI

on: [push]
jobs:
  unittests:
    name: "Unit Tests"
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [2.7, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test]
    - name: Run tests
      run: |
        python setup.py test

  pycodestyle:
    name: "PyCodeStyle"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pycodestyle
    - name: Run pycodestyle
      run: |
        pycodestyle validation setup.py

  pyflakes:
    name: "PyFlakes"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyflakes
    - name: Run pyflakes
      run: |
        pyflakes validation setup.py

  pylint:
    name: "PyLint"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test]
        pip install pylint
    - name: Run pylint
      run: |
        pylint -E validation setup.py

  mypy:
    name: "MyPy"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy types-pytz types-six
    - name: Run mypy
      run: |
        mypy validation

  mypy-py2:
    name: "MyPy (2.7)"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy[python2] types-pytz types-six
    - name: Run mypy (python 2)
      run: |
        mypy --py2 validation

  upload:
    name: "Upload to Python Package Index"
    runs-on: ubuntu-18.04
    if: success() && github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Build source distribution
      run: |
        python setup.py sdist
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
